### ISSUE TITLE
Error al instalar las prácticas

### ISSUE THREAD

**Issue by luisdaniel1987** [ifunam/programacion-estadistica-r#10]
Al ejecutar la línea de instalación de prácticas, me aparece el siguiente mensaje:

> install_course_github("ifunam", "programacion-estadistica-r")
> Downloading: 140 B  
> Error in curl::curl_fetch_memory(url, handle = handle) : 
>   Timeout was reached

**Comment by natorro** [comment]
Es probable que tu conexión sea muy lenta.

**Comment by luisdaniel1987** [comment]
Gracias
