### ISSUE TITLE
Instalación curso error

### ISSUE THREAD

**Issue by Alejazz** [ifunam/programacion-estadistica-r#14]
Hola!
cuando intento instalar el curso en swirl me sale esto:
  Error in unzip(path, list = TRUE) : 
  zip file 'C:/Users/Margarita/Documents/R/win-library/3.4/swirl/Courses/temp.zip' cannot be opened
In addition: Warning message:
In unzip(path, exdir = swirl_courses_dir()) :
  error 1 in extracting from zip file

que debo hacer?

**Comment by natorro** [comment]
Probablemente sea debido a la versión de R que estás usando, el curso se creó cuando la versión de R era la 3.2, te recomiendo instalar esa versión.
